### PR TITLE
feature/logout

### PR DESCRIPTION
**Pull request by S1rDan**
Adds a logout button to the picos menu.

### CODE REVIEW

**Review by mustiwebp — COMMENTED** [review]
I think the corresponding assets are missing.

**Comment by S1rDan** [comment]
> I think the corresponding assets are missing.

Which asset is missing?

**Comment by mustiwebp** [comment]
> > I think the corresponding assets are missing.
> 
> Which asset is missing?

Nevermind. Everything alright.

PR is fair enough.

**Review by mustiwebp — APPROVED** [review]
Looks fine.

**Pull request merged**
