### PR TITLE
Change the color and visibility of the icons on the navigation bar

### PR DESCRIPTION
**Pull request by FaysalSolutions**
1. Match the color of the NavigationBar to the content
2. Change the Icons of the NavigationBar to be more visible

So:
 - fixes issue #54

### CODE REVIEW

**Review by S1rDan — CHANGES_REQUESTED** [review]
You'll have to adjust the bottom bars in screens as well.

This is the bottom bar in my medications as example:


This is the system navigation bar:

**Comment by FaysalSolutions** [comment]
> You'll have to adjust the bottom bars in screens as well.

fixes: [b9f9748](https://github.com/healthcare-it-solutions/picos/pull/146/commits/b9f974872b071be103489a78a29cf343a6e522b7)

**Review by S1rDan — CHANGES_REQUESTED** [review]
You forgot to add the change to pircos_add_button_bar.dart

**Comment by FaysalSolutions** [comment]
> You forgot to add the change to pircos_add_button_bar.dart

Resolved in [db0ccb4](https://github.com/healthcare-it-solutions/picos/pull/146/commits/db0ccb49ce67d3f0a38ca774a7efc8747ddb18a3)

**Review by mustiwebp — APPROVED** [review]

**Pull request merged**
