### PR TITLE
feature/login_feedback

### PR DESCRIPTION
**Pull request by S1rDan**
Loginscreen showing if you've put wrong credentials and providing a small starting framework for more Errorhandling.

### CODE REVIEW

**Comment by FaysalSolutions** [comment]
I get this in the console of my IDE when I try to enter wrong credentials three times, but it would also be nice to have feedback on why I cannot log in, even though I corrected my login credentials:
image

**Comment by mustiwebp** [comment]
1. I noticed that when you type in correct credentials after you entered wrong credentials, the warning text is still displayed. In my opinion, it could lead to a wrong interpretation on the user's side. I would suggest that the warning text should be removed after entering correct credentials.

2. Shouldn't wrong credentials and empty credentials be distinguished?

**Comment by S1rDan** [comment]
> I get this in the console of my IDE when I try to enter wrong credentials three times, but it would also be nice to have feedback on why I cannot log in, even though I corrected my login credentials: image

I'll add a second message for this case.

**Comment by S1rDan** [comment]
> 1. I noticed that when you type in correct credentials after you entered wrong credentials, the warning text is still displayed. In my opinion, it could lead to a wrong interpretation on the user's side. I would suggest that the warning text should be removed after entering correct credentials.
> 
>     2. Shouldn't wrong credentials and empty credentials be distinguished?

1. The app doesn't know if the credentials are correct or not until the response from the server arrives. After that the screen gets discarded anyway. Only thing you could do is to remove the message prematurely, assuming the credentials would be correct. I think I would rather settle for another option. I would just disable the button, so it isn't possible to send multiple requests at once at any time.

2. Why? Empty credentials are wrong.

**Review by FaysalSolutions — APPROVED** [review]

**Review by mustiwebp — APPROVED** [review]

**Pull request merged**
