### PR TITLE
feature/questionaire_limits_values

### PR DESCRIPTION
**Pull request by S1rDan**
Adds limits and checks for blood pressure, blood sugar and heart frequency.

### CODE REVIEW

**Comment by FaysalSolutions** [comment]
Checking the values, everything looks very good. I'm not sure if you're indicating a small hint text with red, so that you can easily identify where something is wrong.
A suggestion from me would be (Maybe an idea for future improvement):

image

I hope that my suggestion/comment is appropriate

**Review by mustiwebp — APPROVED** [review]

**Review by FaysalSolutions — APPROVED** [review]

**Comment by mustiwebp** [comment]
> Checking the values, everything looks very good. I'm not sure if you're indicating a small hint text with red, so that you can easily identify where something is wrong. A suggestion from me would be (Maybe an idea for future improvement):

I think the problem hereby is that the application is not licensed as a medical product. We have to be careful by hightlighting information. Hence red colour shouldn't be used here.

**Comment by FaysalSolutions** [comment]
> > Checking the values, everything looks very good. I'm not sure if you're indicating a small hint text with red, so that you can easily identify where something is wrong. A suggestion from me would be (Maybe an idea for future improvement):
> 
> I think the problem hereby is that the application is not licensed as a medical product. We have to be careful by hightlighting information. Hence red colour shouldn't be used here.

Ah ok, thx for your Infos :)

**Comment by S1rDan** [comment]
> Checking the values, everything looks very good. I'm not sure if you're indicating a small hint text with red, so that you can easily identify where something is wrong. A suggestion from me would be (Maybe an idea for future improvement):
> 
> image
> 
> I hope that my suggestion/comment is appropriate :)

I haven't made any additional text. I'm just replacing the label with the notice.
If the value is too ridiculously out of place, you shouldn't be able to go to the next page.

**Comment by FaysalSolutions** [comment]
> > Checking the values, everything looks very good. I'm not sure if you're indicating a small hint text with red, so that you can easily identify where something is wrong. A suggestion from me would be (Maybe an idea for future improvement):
> > image
> > I hope that my suggestion/comment is appropriate :)
> 
> I haven't made any additional text. I'm just replacing the label with the notice. If the value is too ridiculously out of place, you shouldn't be able to go to the next page.

Alright, thanks for your answer. I will open a new issue for that.

**Pull request merged**
